"use client";
import { useState } from "react";
const pains=[["Wi‑Fi je pomalá","Stránky se načítají věčnost a video se seká."],["Připojení vypadává","Telefon nebo televize se pořád odpojují."],["Signál nedosáhne všude","V ložnici, patře nebo na zahradě Wi‑Fi mizí."],["Zlobí jen jedno zařízení","Ostatní fungují, ale jeden telefon či notebook ne."]];
const steps=[["01","Vyberete, co nefunguje","Žádná učebnice. Začnete rovnou svým problémem."],["02","Projdete doporučené kontroly","Průvodce rozliší Wi‑Fi, internet, pokrytí i konkrétní zařízení."],["03","Uděláte jeden bezpečný krok","Dostanete konkrétní pokyn a popis, jak ověřit výsledek."],["04","Ověříte výsledek","Teprve když krok nepomohl, pokračujete dál."]];
const faqs=[["Musím rozumět sítím nebo routerům?","Ne. Wi‑Fi Doktor je psaný pro běžného člověka. Každý zásah vysvětluje jednoduše a krok po kroku."],["Je to AI, která se připojí k mému routeru?","Ne. Je to interaktivní proklikávací průvodce. Do routeru se sám nepřipojuje a nic bez vašeho vědomí nemění."],["Mohu něco pokazit?","Průvodce začíná bezpečnými kontrolami, mění vždy jen jednu věc a ukazuje, jak ověřit výsledek nebo změnu vrátit."],["Vyřeší každý problém?","Ne každý problém lze vyřešit doma. Pomůže ale rozlišit, zda jde o Wi‑Fi, přípojku, pokrytí nebo zařízení — a kdy už zavolat technika."],["Funguje na telefonu i počítači?","Ano. Průvodce otevřete v běžném prohlížeči a použijete ho tam, kde Wi‑Fi právě řešíte."]];
const Arrow=()=> <span aria-hidden="true">↗</span>;
export default function Home({checkout}:{checkout?:string}){const[open,setOpen]=useState<number|null>(0);return <main>
<header className="nav wrap"><a className="brand" href="#top"><span className="brandMark">W</span><span>Wi‑Fi Doktor</span></a><a className="navCta" href="#objednat">Získat průvodce <Arrow/></a></header>
<section className="hero wrap" id="top"><div className="heroCopy"><p className="eyebrow"><span/> Interaktivní pomoc pro domácí Wi‑Fi</p><h1>Wi‑Fi zlobí?<br/><em>Opravte ji sami.</em></h1><p className="lead">Zjistěte, proč je vaše Wi‑Fi pomalá, vypadává nebo nedosáhne všude. Bez technických znalostí. Krok za krokem.</p><div className="heroActions"><a className="primary" href="#objednat">Chci vyřešit Wi‑Fi <Arrow/></a><a className="textLink" href="#jak">Jak to funguje ↓</a></div><div className="trustRow"><span>✓ Bez instalace</span><span>✓ Lidsky vysvětlené</span><span>✓ Bez zásahu naslepo</span></div></div>
<div className="productMock"><div className="mockTop"><span className="mockLogo">W</span><span>Diagnostika</span><span className="stepPill">Ukázka postupu</span></div><div className="mockProgress"><i/></div><div className="mockBody"><span className="signal">⌁</span><p className="smallLabel">RYCHLÁ KONTROLA</p><h2>Kde Wi‑Fi<br/>zlobí nejvíc?</h2><div className="mockOption">Jen dál od routeru <span>→</span></div><div className="mockOption">Také blízko routeru <span>→</span></div><div className="mockOption">Jen na jednom zařízení <span>→</span></div><p className="safe">● Zatím nic neměníme. Nejdřív zjistíme příčinu.</p></div></div></section>
<section className="problemBand"><div className="wrap"><p className="sectionKicker">Poznáváte to?</p><div className="painGrid">{pains.map(([t,b],i)=><article key={t}><b>0{i+1}</b><h3>{t}</h3><p>{b}</p></article>)}</div></div></section>
<section className="how wrap" id="jak"><div className="sectionHead"><p className="eyebrow"><span/> Jak to funguje</p><h2>Žádné hádání.<br/><em>Jeden krok po druhém.</em></h2><p>Wi‑Fi Doktor vás nezahltí pojmy. Podle vybraného problému ukáže konkrétní kontroly a kroky.</p></div><div className="steps">{steps.map(([n,t,b])=><article key={n}><span>{n}</span><div><h3>{t}</h3><p>{b}</p></div></article>)}</div></section>
<section className="inside"><div className="wrap insideGrid"><div><p className="eyebrow light"><span/> Co získáte</p><h2>Technikův postup.<br/><em>Normální řečí.</em></h2><p className="insideLead">U každého kroku přesně víte čtyři věci:</p><div className="formula"><span>CO</span><i>→</i><span>KDE</span><i>→</i><span>PROČ</span><i>→</i><span>OVĚŘIT</span></div></div><ul><li><b>Rozlišení příčiny</b><span>Wi‑Fi, přípojka, pokrytí nebo zařízení</span></li><li><b>Návody bez zkratek</b><span>Kam kliknout a co přesně zvolit</span></li><li><b>Bezpečné změny</b><span>Jedna úprava, jeden test, možnost návratu</span></li><li><b>Jasný další krok</b><span>I když už je potřeba poskytovatel či technik</span></li></ul></div></section>
<section className="truth wrap"><div className="truthCard"><span className="quote">„</span><div><p>Neprodáváme vám další chytrou krabičku.</p><h2>Nejdřív zjistíte, co je skutečně špatně. Možná nový router vůbec nepotřebujete.</h2></div></div></section>
<section className="offer wrap" id="objednat"><div className="offerCopy"><p className="eyebrow"><span/> Wi‑Fi Doktor</p><h2>Méně nervů.<br/><em>Více funkční Wi‑Fi.</em></h2><p>Jednorázový přístup k interaktivnímu průvodci pro běžné problémy domácí Wi‑Fi.</p><div className="featureChips"><span>Pomalá Wi‑Fi</span><span>Výpadky</span><span>Slabý signál</span><span>Jedno zařízení</span></div></div><div className="priceCard">{checkout==="error"&&<p className="checkoutNotice" role="alert">Platbu se nepodařilo připravit. Zkuste to za chvíli. Pokud jste již zaplatili, použijte potvrzení objednávky a neplaťte znovu.</p>}{checkout==="cancelled"&&<p className="checkoutNotice" role="status">Platba byla přerušena. Objednávku můžete dokončit tlačítkem níže.</p>}<p>JEDNORÁZOVÝ PŘÍSTUP</p><div className="price"><strong>299</strong><span>Kč</span></div><small>Žádné předplatné</small><form action="/api/checkout" method="post"><button className="primary full" type="submit">Koupit bezpečně přes Stripe <Arrow/></button></form><ul><li>✓ Potvrzení platby ihned</li><li>✓ Použití na mobilu i počítači</li><li>✓ Lidské vysvětlení každého kroku</li></ul><p className="note">Bezpečná jednorázová platba. Platební údaje zadáváte přímo na stránce Stripe.</p></div></section>
<section className="faq wrap"><div className="sectionHead compact"><p className="eyebrow"><span/> Časté otázky</p><h2>Než začnete.</h2></div><div className="faqList">{faqs.map(([q,a],i)=><div className="faqItem" key={q}><button onClick={()=>setOpen(open===i?null:i)} aria-expanded={open===i}><span>{q}</span><b>{open===i?"−":"+"}</b></button>{open===i&&<p>{a}</p>}</div>)}</div></section>
<section className="finalCta"><div className="wrap"><p className="eyebrow light"><span/> Udělejte první krok</p><h2>Než koupíte nový router,<br/><em>zjistěte, kde je problém.</em></h2><a className="primary white" href="#objednat">Chci vyřešit Wi‑Fi <Arrow/></a></div></section>
<footer className="wrap"><a className="brand" href="#top"><span className="brandMark">W</span><span>Wi‑Fi Doktor</span></a><nav className="footerLinks"><a href="/obchodni-podminky">Obchodní podmínky</a><a href="/ochrana-soukromi">Ochrana soukromí</a></nav><span>© 2026</span></footer><form className="mobileBuyForm" action="/api/checkout" method="post"><button className="mobileBuy" type="submit">Koupit Wi‑Fi Doktora · 299 Kč <Arrow/></button></form></main>}
